import type { Song } from "./types";

export type {
  LyricLine,
  Song,
  SongForm,
  SongGenre,
  SongNote,
  SongSection,
  SongSectionKind,
} from "./types";

/**
 * The free songbook. Every melody here is public domain — the `publicDomain`
 * field on each entry says why, because that is the constraint the whole
 * catalog is built around.
 *
 * The house style is one short opening phrase (`form: "phrase"`), looped four
 * times, so a practice rep stays tight and repeatable. Full multi-section
 * arrangements set `form: "full"` and `defaultLoops: 1`.
 */
export const SONGS: Song[] = [
  {
    id: "twinkle",
    slug: "twinkle-twinkle-little-star",
    title: "Twinkle Twinkle Little Star",
    origin: "Traditional (French melody, English lyrics 1806)",
    publicDomain:
      "Melody from the French air “Ah! vous dirai-je, Maman” (1761); English lyrics by Jane Taylor (1806). Both long out of copyright.",
    bpm: 100,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Nursery",
    era: "1700s",
    language: "English",
    tags: ["first song", "stepwise", "narrow range"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "Twin", wordEnd: false },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "kle" },
      { midi: 67, startBeat: 2, durBeats: 1, lyric: "twin", wordEnd: false },
      { midi: 67, startBeat: 3, durBeats: 1, lyric: "kle" },
      { midi: 69, startBeat: 4, durBeats: 1, lyric: "lit", wordEnd: false },
      { midi: 69, startBeat: 5, durBeats: 1, lyric: "tle" },
      { midi: 67, startBeat: 6, durBeats: 2, lyric: "star" },
      { midi: 65, startBeat: 8, durBeats: 1, lyric: "how", line: 1 },
      { midi: 65, startBeat: 9, durBeats: 1, lyric: "I", line: 1 },
      { midi: 64, startBeat: 10, durBeats: 1, lyric: "won", line: 1, wordEnd: false },
      { midi: 64, startBeat: 11, durBeats: 1, lyric: "der", line: 1 },
      { midi: 62, startBeat: 12, durBeats: 1, lyric: "what", line: 1 },
      { midi: 62, startBeat: 13, durBeats: 1, lyric: "you", line: 1 },
      { midi: 60, startBeat: 14, durBeats: 2, lyric: "are", line: 1 },
    ],
  },
  {
    id: "ode-to-joy",
    slug: "ode-to-joy",
    title: "Ode to Joy",
    origin: "Beethoven, Symphony No. 9 (1824); hymn text 1907",
    publicDomain:
      "Beethoven’s melody dates from 1824 and he died in 1827; the “Joyful, joyful” hymn text by Henry van Dyke was published in 1907.",
    bpm: 120,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Classical",
    era: "1800s",
    language: "English",
    tags: ["stepwise", "narrow range", "hymn"],
    notes: [
      { midi: 64, startBeat: 0, durBeats: 1, lyric: "Joy", wordEnd: false },
      { midi: 64, startBeat: 1, durBeats: 1, lyric: "ful," },
      { midi: 65, startBeat: 2, durBeats: 1, lyric: "joy", wordEnd: false },
      { midi: 67, startBeat: 3, durBeats: 1, lyric: "ful," },
      { midi: 67, startBeat: 4, durBeats: 1, lyric: "we" },
      { midi: 65, startBeat: 5, durBeats: 1, lyric: "a", wordEnd: false },
      { midi: 64, startBeat: 6, durBeats: 1, lyric: "dore" },
      { midi: 62, startBeat: 7, durBeats: 2, lyric: "thee" },
    ],
  },
  {
    id: "row-row-row",
    slug: "row-row-row-your-boat",
    title: "Row Row Row Your Boat",
    origin: "Traditional (American round, published 1852)",
    publicDomain:
      "Traditional American round, in print since 1852 and never under active copyright.",
    bpm: 76,
    beatsPerBar: 3,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Nursery",
    era: "1800s",
    language: "English",
    tags: ["round", "stepwise", "narrow range"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "Row," },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "row," },
      { midi: 60, startBeat: 2, durBeats: 1, lyric: "row" },
      { midi: 62, startBeat: 3, durBeats: 1, lyric: "your" },
      { midi: 64, startBeat: 4, durBeats: 1, lyric: "boat," },
      { midi: 64, startBeat: 5, durBeats: 1, lyric: "gent", wordEnd: false },
      { midi: 62, startBeat: 6, durBeats: 1, lyric: "ly" },
      { midi: 64, startBeat: 7, durBeats: 1, lyric: "down" },
      { midi: 65, startBeat: 8, durBeats: 1, lyric: "the" },
      { midi: 67, startBeat: 9, durBeats: 2, lyric: "stream" },
    ],
  },
  {
    id: "mary-lamb",
    slug: "mary-had-a-little-lamb",
    title: "Mary Had a Little Lamb",
    origin: "Traditional (Sarah Josepha Hale, 1830)",
    publicDomain:
      "Lyrics published by Sarah Josepha Hale in 1830; the melody is a traditional tune of the same period.",
    bpm: 104,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Nursery",
    era: "1800s",
    language: "English",
    tags: ["first song", "stepwise", "narrow range"],
    notes: [
      { midi: 64, startBeat: 0, durBeats: 1, lyric: "Ma", wordEnd: false },
      { midi: 62, startBeat: 1, durBeats: 1, lyric: "ry" },
      { midi: 60, startBeat: 2, durBeats: 1, lyric: "had" },
      { midi: 62, startBeat: 3, durBeats: 1, lyric: "a" },
      { midi: 64, startBeat: 4, durBeats: 1, lyric: "lit", wordEnd: false },
      { midi: 64, startBeat: 5, durBeats: 1, lyric: "tle" },
      { midi: 64, startBeat: 6, durBeats: 1, lyric: "lamb," },
      { midi: 62, startBeat: 7, durBeats: 1, lyric: "lit", line: 1, wordEnd: false },
      { midi: 62, startBeat: 8, durBeats: 1, lyric: "tle", line: 1 },
      { midi: 62, startBeat: 9, durBeats: 1, lyric: "lamb,", line: 1 },
      { midi: 64, startBeat: 10, durBeats: 1, lyric: "lit", line: 1, wordEnd: false },
      { midi: 67, startBeat: 11, durBeats: 1, lyric: "tle", line: 1 },
      { midi: 67, startBeat: 12, durBeats: 2, lyric: "lamb", line: 1 },
    ],
  },
  {
    id: "frere-jacques",
    slug: "frere-jacques",
    title: "Frère Jacques",
    origin: "Traditional (French round, 18th century)",
    publicDomain:
      "Traditional French round, in circulation since the 18th century.",
    bpm: 120,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Nursery",
    era: "1700s",
    language: "French",
    tags: ["round", "stepwise", "narrow range"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "Frè", wordEnd: false },
      { midi: 62, startBeat: 1, durBeats: 1, lyric: "re" },
      { midi: 64, startBeat: 2, durBeats: 1, lyric: "Jac", wordEnd: false },
      { midi: 60, startBeat: 3, durBeats: 1, lyric: "ques," },
      { midi: 60, startBeat: 4, durBeats: 1, lyric: "Frè", wordEnd: false },
      { midi: 62, startBeat: 5, durBeats: 1, lyric: "re" },
      { midi: 64, startBeat: 6, durBeats: 1, lyric: "Jac", wordEnd: false },
      { midi: 60, startBeat: 7, durBeats: 1, lyric: "ques" },
    ],
  },
  {
    id: "london-bridge",
    slug: "london-bridge-is-falling-down",
    title: "London Bridge Is Falling Down",
    origin: "Traditional (English nursery rhyme)",
    publicDomain:
      "Traditional English nursery rhyme, printed since the 18th century.",
    bpm: 104,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Nursery",
    era: "1700s",
    language: "English",
    tags: ["stepwise", "playground"],
    notes: [
      { midi: 67, startBeat: 0, durBeats: 1, lyric: "Lon", wordEnd: false },
      { midi: 69, startBeat: 1, durBeats: 1, lyric: "don" },
      { midi: 67, startBeat: 2, durBeats: 1, lyric: "Bridge" },
      { midi: 65, startBeat: 3, durBeats: 1, lyric: "is" },
      { midi: 64, startBeat: 4, durBeats: 1, lyric: "fall", wordEnd: false },
      { midi: 65, startBeat: 5, durBeats: 1, lyric: "ing" },
      { midi: 67, startBeat: 6, durBeats: 1, lyric: "down," },
      { midi: 62, startBeat: 7, durBeats: 1, lyric: "fall", line: 1, wordEnd: false },
      { midi: 64, startBeat: 8, durBeats: 1, lyric: "ing", line: 1 },
      { midi: 65, startBeat: 9, durBeats: 1, lyric: "down,", line: 1 },
      { midi: 67, startBeat: 10, durBeats: 1, lyric: "fall", line: 1, wordEnd: false },
      { midi: 64, startBeat: 11, durBeats: 1, lyric: "ing", line: 1 },
      { midi: 60, startBeat: 12, durBeats: 2, lyric: "down", line: 1 },
    ],
  },
  {
    // Rising 4th from the dominant-below to the tonic, repeated each phrase,
    // plus a dip to the low submediant on "sound" — Hard despite the slow tempo.
    id: "amazing-grace",
    slug: "amazing-grace",
    title: "Amazing Grace",
    origin: "Traditional tune “New Britain” (American shape-note, printed 1829); words by John Newton, 1779",
    publicDomain:
      "John Newton’s hymn text was published in 1779; the “New Britain” tune it is now sung to first appeared in an 1829 shape-note tunebook. Both are centuries out of copyright.",
    bpm: 70,
    beatsPerBar: 3,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Hymn",
    era: "1700s",
    language: "English",
    tags: ["hymn", "wide range", "leap"],
    notes: [
      { midi: 67, startBeat: 0, durBeats: 1, lyric: "A", wordEnd: false },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "maz", wordEnd: false },
      { midi: 64, startBeat: 2, durBeats: 1, lyric: "ing" },
      { midi: 60, startBeat: 3, durBeats: 2, lyric: "grace," },
      { midi: 64, startBeat: 5, durBeats: 1, lyric: "how" },
      { midi: 62, startBeat: 6, durBeats: 1, lyric: "sweet" },
      { midi: 60, startBeat: 7, durBeats: 1, lyric: "the" },
      { midi: 57, startBeat: 8, durBeats: 2, lyric: "sound," },
      { midi: 67, startBeat: 10, durBeats: 1, lyric: "that", line: 1 },
      { midi: 60, startBeat: 11, durBeats: 1, lyric: "saved", line: 1 },
      { midi: 64, startBeat: 12, durBeats: 1, lyric: "a", line: 1 },
      { midi: 60, startBeat: 13, durBeats: 1, lyric: "wretch", line: 1 },
      { midi: 64, startBeat: 14, durBeats: 1, lyric: "like", line: 1 },
      { midi: 62, startBeat: 15, durBeats: 3, lyric: "me", line: 1 },
    ],
  },
  {
    // Stepwise until the octave-ish leap up to "ac-QUAINT-ance" — Hard on
    // range even though the rest of the phrase walks back down calmly.
    id: "auld-lang-syne",
    slug: "auld-lang-syne",
    title: "Auld Lang Syne",
    origin: "Traditional Scottish tune; words by Robert Burns, 1788",
    publicDomain:
      "Robert Burns wrote the verses in 1788 and died in 1796; the melody is an older traditional Scottish air. Both are long out of copyright.",
    bpm: 100,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Traditional",
    era: "1700s",
    language: "English",
    tags: ["traditional", "wide range", "new year"],
    notes: [
      { midi: 67, startBeat: 0, durBeats: 1, lyric: "Should" },
      { midi: 67, startBeat: 1, durBeats: 1, lyric: "auld" },
      { midi: 72, startBeat: 2, durBeats: 1, lyric: "ac", wordEnd: false },
      { midi: 69, startBeat: 3, durBeats: 1, lyric: "quaint" },
      { midi: 67, startBeat: 4, durBeats: 1, lyric: "ance" },
      { midi: 64, startBeat: 5, durBeats: 1, lyric: "be" },
      { midi: 62, startBeat: 6, durBeats: 1, lyric: "for", wordEnd: false },
      { midi: 60, startBeat: 7, durBeats: 1, lyric: "got" },
      { midi: 64, startBeat: 8, durBeats: 1, lyric: "and", line: 1 },
      { midi: 67, startBeat: 9, durBeats: 1, lyric: "ne", line: 1, wordEnd: false },
      { midi: 69, startBeat: 10, durBeats: 1, lyric: "ver", line: 1 },
      { midi: 67, startBeat: 11, durBeats: 1, lyric: "brought", line: 1 },
      { midi: 64, startBeat: 12, durBeats: 1, lyric: "to", line: 1 },
      { midi: 62, startBeat: 13, durBeats: 3, lyric: "mind?", line: 1 },
    ],
  },
  {
    // Five notes, one fifth-leap on "home, home" — short but the leap alone
    // is enough to push it past Easy.
    id: "home-on-the-range",
    slug: "home-on-the-range",
    title: "Home on the Range",
    origin: "Poem “My Western Home” by Dr. Brewster Higley, 1873; melody by Daniel E. Kelley, 1873",
    publicDomain:
      "Higley’s poem and Kelley’s melody were both published in 1873; Higley died in 1911 and Kelley in 1905 — long out of copyright.",
    bpm: 96,
    beatsPerBar: 3,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Folk",
    era: "1800s",
    language: "English",
    tags: ["cowboy song", "leap", "chorus hook"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 2, lyric: "Home," },
      { midi: 67, startBeat: 2, durBeats: 1, lyric: "home" },
      { midi: 64, startBeat: 3, durBeats: 1, lyric: "on" },
      { midi: 62, startBeat: 4, durBeats: 1, lyric: "the" },
      { midi: 60, startBeat: 5, durBeats: 3, lyric: "range," },
    ],
  },
  {
    // Full arrangement: the gently descending verse ("Oh, give me a home")
    // leads into the familiar leaping chorus. Verse and chorus together push
    // this to Hard on range even though each half alone is calmer.
    id: "home-on-the-range-full",
    slug: "home-on-the-range-full",
    title: "Home on the Range (Verse & Chorus)",
    origin: "Poem “My Western Home” by Dr. Brewster Higley, 1873; melody by Daniel E. Kelley, 1873",
    publicDomain:
      "Higley’s poem and Kelley’s melody were both published in 1873; Higley died in 1911 and Kelley in 1905 — long out of copyright.",
    bpm: 96,
    beatsPerBar: 3,
    defaultKeyRootMidi: 60,
    form: "full",
    defaultLoops: 1,
    genre: "Folk",
    era: "1800s",
    language: "English",
    tags: ["cowboy song", "full song", "verse and chorus"],
    arrangementOf: "home-on-the-range",
    notes: [
      { midi: 64, startBeat: 0, durBeats: 1, lyric: "Oh," },
      { midi: 64, startBeat: 1, durBeats: 1, lyric: "give" },
      { midi: 64, startBeat: 2, durBeats: 1, lyric: "me" },
      { midi: 65, startBeat: 3, durBeats: 1, lyric: "a" },
      { midi: 67, startBeat: 4, durBeats: 2, lyric: "home," },
      { midi: 65, startBeat: 6, durBeats: 1, lyric: "where" },
      { midi: 64, startBeat: 7, durBeats: 1, lyric: "the" },
      { midi: 62, startBeat: 8, durBeats: 1, lyric: "buf", wordEnd: false },
      { midi: 60, startBeat: 9, durBeats: 1, lyric: "fa", wordEnd: false },
      { midi: 59, startBeat: 10, durBeats: 1, lyric: "lo" },
      { midi: 60, startBeat: 11, durBeats: 2, lyric: "roam," },
      { midi: 60, startBeat: 13, durBeats: 2, lyric: "Home,", line: 1 },
      { midi: 67, startBeat: 15, durBeats: 1, lyric: "home", line: 1 },
      { midi: 64, startBeat: 16, durBeats: 1, lyric: "on", line: 1 },
      { midi: 62, startBeat: 17, durBeats: 1, lyric: "the", line: 1 },
      { midi: 60, startBeat: 18, durBeats: 3, lyric: "range,", line: 1 },
    ],
    sections: [
      { kind: "verse", label: "Verse 1", startBeat: 0, endBeat: 13 },
      { kind: "chorus", label: "Chorus", startBeat: 13, endBeat: 21 },
    ],
  },
  {
    // Mostly narrow and repeated-note, but three 4th-plus leaps ("dle WENT",
    // "TO town", "po-NY") keep it Hard rather than Easy.
    id: "yankee-doodle",
    slug: "yankee-doodle",
    title: "Yankee Doodle",
    origin: "Traditional tune of English/colonial origin, popularized in America during the Revolutionary War, 18th century",
    publicDomain:
      "Traditional 18th-century march tune of unknown authorship, in circulation since well before the United States existed.",
    bpm: 112,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Patriotic",
    era: "1700s",
    language: "English",
    tags: ["march", "narrow range", "stepwise"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "Yan", wordEnd: false },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "kee" },
      { midi: 62, startBeat: 2, durBeats: 1, lyric: "Doo", wordEnd: false },
      { midi: 64, startBeat: 3, durBeats: 1, lyric: "dle" },
      { midi: 60, startBeat: 4, durBeats: 1, lyric: "went" },
      { midi: 64, startBeat: 5, durBeats: 1, lyric: "to" },
      { midi: 62, startBeat: 6, durBeats: 2, lyric: "town," },
      { midi: 60, startBeat: 8, durBeats: 1, lyric: "ri", line: 1, wordEnd: false },
      { midi: 60, startBeat: 9, durBeats: 1, lyric: "ding", line: 1 },
      { midi: 62, startBeat: 10, durBeats: 1, lyric: "on", line: 1 },
      { midi: 64, startBeat: 11, durBeats: 1, lyric: "a", line: 1 },
      { midi: 59, startBeat: 12, durBeats: 1, lyric: "po", line: 1, wordEnd: false },
      { midi: 60, startBeat: 13, durBeats: 2, lyric: "ny", line: 1 },
    ],
  },
  {
    // Repeated tonic then a fifth leap up on "ald HAD" — Medium range but
    // that one leap is enough to land it in Hard.
    id: "old-macdonald",
    slug: "old-macdonald-had-a-farm",
    title: "Old MacDonald Had a Farm",
    origin: "Traditional (American/British nursery song; documented variants predate 1917)",
    publicDomain:
      "Traditional nursery song of unknown authorship, documented under earlier titles (“Ohio”, “The Farmyard Song”) since before 1917.",
    bpm: 108,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Nursery",
    era: "Traditional",
    language: "English",
    tags: ["first song", "farm", "leap"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "Old" },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "Mac", wordEnd: false },
      { midi: 60, startBeat: 2, durBeats: 1, lyric: "Don", wordEnd: false },
      { midi: 67, startBeat: 3, durBeats: 1, lyric: "ald" },
      { midi: 67, startBeat: 4, durBeats: 1, lyric: "had" },
      { midi: 69, startBeat: 5, durBeats: 1, lyric: "a" },
      { midi: 67, startBeat: 6, durBeats: 2, lyric: "farm," },
    ],
  },
  {
    // A repeated-note figure that steps down a third and back — genuinely
    // Easy, good for a first Christmas song.
    id: "silent-night",
    slug: "silent-night",
    title: "Silent Night",
    origin: "Melody by Franz Xaver Gruber, 1818; German words by Joseph Mohr, 1816; English translation by John Freeman Young, 1859",
    publicDomain:
      "Gruber (d. 1863) composed the tune in 1818 for Mohr’s 1816 text; the standard English translation dates to 1859. All are long out of copyright.",
    bpm: 66,
    beatsPerBar: 3,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Christmas",
    era: "1800s",
    language: "English",
    tags: ["christmas", "lullaby", "narrow range"],
    notes: [
      { midi: 67, startBeat: 0, durBeats: 1, lyric: "Si", wordEnd: false },
      { midi: 67, startBeat: 1, durBeats: 1, lyric: "lent" },
      { midi: 64, startBeat: 2, durBeats: 2, lyric: "night," },
      { midi: 67, startBeat: 4, durBeats: 1, lyric: "ho", line: 1, wordEnd: false },
      { midi: 67, startBeat: 5, durBeats: 1, lyric: "ly", line: 1 },
      { midi: 64, startBeat: 6, durBeats: 2, lyric: "night,", line: 1 },
    ],
  },
  {
    // Narrow-range spiritual except for the rising leap into "march-ing" and
    // back — that pair of leaps is what makes it Hard.
    id: "when-the-saints",
    slug: "when-the-saints-go-marching-in",
    title: "When the Saints Go Marching In",
    origin: "Traditional African American spiritual, 19th-century roots; popularized in New Orleans jazz",
    publicDomain:
      "Traditional spiritual of unknown authorship, documented since the 19th century; no copyrighted arrangement is used here.",
    bpm: 120,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Spiritual",
    era: "1800s",
    language: "English",
    tags: ["spiritual", "leap", "upbeat"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "Oh" },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "when" },
      { midi: 60, startBeat: 2, durBeats: 1, lyric: "the" },
      { midi: 64, startBeat: 3, durBeats: 1, lyric: "saints" },
      { midi: 64, startBeat: 4, durBeats: 1, lyric: "go" },
      { midi: 67, startBeat: 5, durBeats: 1, lyric: "march", wordEnd: false },
      { midi: 64, startBeat: 6, durBeats: 1, lyric: "ing" },
      { midi: 60, startBeat: 7, durBeats: 2, lyric: "in," },
    ],
  },
  {
    // Stepwise waltz descent; Hard only because of the final leap home to
    // the tonic on "low."
    id: "down-in-the-valley",
    slug: "down-in-the-valley",
    title: "Down in the Valley",
    origin: "Traditional American folk ballad, Appalachian roots, collected in the early 20th century",
    publicDomain:
      "Traditional Appalachian folk song of unknown authorship, collected and published without any copyright claim.",
    bpm: 90,
    beatsPerBar: 3,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Folk",
    era: "1800s",
    language: "English",
    tags: ["ballad", "waltz", "stepwise"],
    notes: [
      { midi: 67, startBeat: 0, durBeats: 1, lyric: "Down" },
      { midi: 64, startBeat: 1, durBeats: 1, lyric: "in" },
      { midi: 62, startBeat: 2, durBeats: 1, lyric: "the" },
      { midi: 60, startBeat: 3, durBeats: 1, lyric: "val", wordEnd: false },
      { midi: 60, startBeat: 4, durBeats: 1, lyric: "ley," },
      { midi: 62, startBeat: 5, durBeats: 1, lyric: "the" },
      { midi: 64, startBeat: 6, durBeats: 1, lyric: "val", wordEnd: false },
      { midi: 65, startBeat: 7, durBeats: 1, lyric: "ley" },
      { midi: 64, startBeat: 8, durBeats: 1, lyric: "so" },
      { midi: 60, startBeat: 9, durBeats: 2, lyric: "low," },
    ],
  },
  {
    // Repeated-note verse is easy to sing; one leap up to "round the
    // mountain" nudges it to Hard.
    id: "shell-be-coming",
    slug: "shell-be-coming-round-the-mountain",
    title: "She'll Be Coming Round the Mountain",
    origin: "Traditional American folk song, derived from the 19th-century spiritual “When the Chariot Comes”",
    publicDomain:
      "Traditional folk song of unknown authorship, documented since the 19th century.",
    bpm: 128,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Folk",
    era: "1800s",
    language: "English",
    tags: ["folk", "repeated note", "playful"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "She'll" },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "be" },
      { midi: 64, startBeat: 2, durBeats: 1, lyric: "com", wordEnd: false },
      { midi: 64, startBeat: 3, durBeats: 1, lyric: "in'" },
      { midi: 67, startBeat: 4, durBeats: 1, lyric: "round" },
      { midi: 67, startBeat: 5, durBeats: 1, lyric: "the" },
      { midi: 67, startBeat: 6, durBeats: 1, lyric: "moun", wordEnd: false },
      { midi: 64, startBeat: 7, durBeats: 1, lyric: "tain" },
      { midi: 62, startBeat: 8, durBeats: 1, lyric: "when" },
      { midi: 60, startBeat: 9, durBeats: 1, lyric: "she" },
      { midi: 60, startBeat: 10, durBeats: 2, lyric: "comes," },
    ],
  },
  {
    // Entirely stepwise, true to the song's own "gift to be simple" —
    // Medium on range alone, no leaps at all.
    id: "simple-gifts",
    slug: "simple-gifts",
    title: "Simple Gifts",
    origin: "Shaker song by Elder Joseph Brackett, 1848",
    publicDomain: "Written by Joseph Brackett in 1848; he died in 1882. Long out of copyright.",
    bpm: 112,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Traditional",
    era: "1800s",
    language: "English",
    tags: ["shaker", "stepwise", "narrow range"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "'Tis" },
      { midi: 62, startBeat: 1, durBeats: 1, lyric: "the" },
      { midi: 64, startBeat: 2, durBeats: 1, lyric: "gift" },
      { midi: 65, startBeat: 3, durBeats: 1, lyric: "to" },
      { midi: 67, startBeat: 4, durBeats: 1, lyric: "be" },
      { midi: 65, startBeat: 5, durBeats: 1, lyric: "sim", wordEnd: false },
      { midi: 64, startBeat: 6, durBeats: 1, lyric: "ple," },
      { midi: 62, startBeat: 7, durBeats: 1, lyric: "'tis", line: 1 },
      { midi: 60, startBeat: 8, durBeats: 1, lyric: "the", line: 1 },
      { midi: 62, startBeat: 9, durBeats: 1, lyric: "gift", line: 1 },
      { midi: 64, startBeat: 10, durBeats: 1, lyric: "to", line: 1 },
      { midi: 65, startBeat: 11, durBeats: 1, lyric: "be", line: 1 },
      { midi: 67, startBeat: 12, durBeats: 2, lyric: "free,", line: 1 },
    ],
  },
  {
    // The octave-ish reach up to "bird" before settling back is the main
    // challenge — Hard on range.
    id: "aura-lee",
    slug: "aura-lee",
    title: "Aura Lee",
    origin: "Music by George R. Poulton, lyrics by W. W. Fosdick, 1861",
    publicDomain: "Published in 1861; Poulton died in 1867 and Fosdick in 1862. Long out of copyright.",
    bpm: 88,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Traditional",
    era: "1800s",
    language: "English",
    tags: ["ballad", "wide range", "leap"],
    notes: [
      { midi: 64, startBeat: 0, durBeats: 1, lyric: "As" },
      { midi: 64, startBeat: 1, durBeats: 1, lyric: "the" },
      { midi: 67, startBeat: 2, durBeats: 1, lyric: "black", wordEnd: false },
      { midi: 72, startBeat: 3, durBeats: 1, lyric: "bird" },
      { midi: 69, startBeat: 4, durBeats: 1, lyric: "in" },
      { midi: 67, startBeat: 5, durBeats: 1, lyric: "the" },
      { midi: 64, startBeat: 6, durBeats: 2, lyric: "spring," },
      { midi: 64, startBeat: 8, durBeats: 1, lyric: "'neath", line: 1 },
      { midi: 67, startBeat: 9, durBeats: 1, lyric: "the", line: 1 },
      { midi: 69, startBeat: 10, durBeats: 1, lyric: "wil", line: 1, wordEnd: false },
      { midi: 67, startBeat: 11, durBeats: 1, lyric: "low", line: 1 },
      { midi: 64, startBeat: 12, durBeats: 3, lyric: "tree,", line: 1 },
    ],
  },
  {
    // Lilting and mostly stepwise; the leap on the second "bonnie" keeps it
    // out of Easy.
    id: "loch-lomond",
    slug: "loch-lomond",
    title: "Loch Lomond",
    origin: "Traditional Scottish folk song, in print since the 19th century",
    publicDomain: "Traditional Scottish song of unknown authorship, published since at least 1841.",
    bpm: 100,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Folk",
    era: "1700s",
    language: "English",
    tags: ["scottish", "ballad", "leap"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "By" },
      { midi: 62, startBeat: 1, durBeats: 1, lyric: "yon" },
      { midi: 65, startBeat: 2, durBeats: 1, lyric: "bon", wordEnd: false },
      { midi: 67, startBeat: 3, durBeats: 1, lyric: "nie" },
      { midi: 65, startBeat: 4, durBeats: 1, lyric: "banks," },
      { midi: 64, startBeat: 5, durBeats: 1, lyric: "and" },
      { midi: 62, startBeat: 6, durBeats: 1, lyric: "by" },
      { midi: 60, startBeat: 7, durBeats: 1, lyric: "yon" },
      { midi: 64, startBeat: 8, durBeats: 1, lyric: "bon", wordEnd: false },
      { midi: 67, startBeat: 9, durBeats: 1, lyric: "nie" },
      { midi: 65, startBeat: 10, durBeats: 2, lyric: "braes," },
    ],
  },
  {
    // Slow tempo doesn't hide the two leaps that open and close the
    // phrase — Hard, expressive spiritual.
    id: "deep-river",
    slug: "deep-river",
    title: "Deep River",
    origin: "Traditional African American spiritual, documented in the 19th century",
    publicDomain:
      "Traditional spiritual of unknown authorship; earliest printed collections date to the 1870s, long out of copyright.",
    bpm: 60,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Spiritual",
    era: "1800s",
    language: "English",
    tags: ["spiritual", "legato", "leap"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "Deep" },
      { midi: 64, startBeat: 1, durBeats: 1, lyric: "riv", wordEnd: false },
      { midi: 67, startBeat: 2, durBeats: 1, lyric: "er," },
      { midi: 65, startBeat: 3, durBeats: 1, lyric: "my" },
      { midi: 64, startBeat: 4, durBeats: 1, lyric: "home" },
      { midi: 62, startBeat: 5, durBeats: 1, lyric: "is" },
      { midi: 64, startBeat: 6, durBeats: 1, lyric: "o", wordEnd: false },
      { midi: 60, startBeat: 7, durBeats: 1, lyric: "ver" },
      { midi: 62, startBeat: 8, durBeats: 1, lyric: "Jor", wordEnd: false },
      { midi: 60, startBeat: 9, durBeats: 3, lyric: "dan," },
    ],
  },
];

/**
 * The Pro songbook — same house style, gated to Pro members.
 *
 * Membership in this array IS the paywall: `songs-client` refuses to start
 * anything that is not in `SONGS` unless Pro is active. Moving an entry
 * between the two arrays changes who can sing it, so treat the split as
 * access control, not as categorisation.
 *
 * Titles must stay exactly as the teaser cards spell them: the title is the
 * key best-scores are stored under.
 */
export const PRO_SONGS: Song[] = [
  {
    // Contour: rising step opening, phrase peak on "call" — Medium (span 14 st).
    id: "danny-boy",
    slug: "danny-boy",
    title: "Danny Boy",
    origin: "Traditional (Londonderry Air, publ. 1855); lyrics Frederic Weatherly, 1913",
    publicDomain:
      "The Londonderry Air melody was published in 1855; Frederic Weatherly’s lyrics date from 1913, before the 1929 US public-domain cutoff.",
    bpm: 63,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Folk",
    era: "1800s",
    language: "English",
    tags: ["ballad", "wide range", "legato"],
    notes: [
      { midi: 55, startBeat: 0, durBeats: 1, lyric: "Oh" },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "Dan", wordEnd: false },
      { midi: 62, startBeat: 2, durBeats: 1, lyric: "ny" },
      { midi: 64, startBeat: 3, durBeats: 2, lyric: "boy," },
      { midi: 64, startBeat: 5, durBeats: 1, lyric: "the" },
      { midi: 65, startBeat: 6, durBeats: 1, lyric: "pipes," },
      { midi: 64, startBeat: 7, durBeats: 1, lyric: "the" },
      { midi: 65, startBeat: 8, durBeats: 1, lyric: "pipes" },
      { midi: 67, startBeat: 9, durBeats: 1, lyric: "are" },
      { midi: 69, startBeat: 10, durBeats: 2, lyric: "call", wordEnd: false },
      { midi: 67, startBeat: 12, durBeats: 2, lyric: "ing" },
    ],
  },
  {
    // Long held tones over a gentle arch — Easy tempo, Medium reach to A4.
    id: "shenandoah",
    slug: "shenandoah",
    title: "Shenandoah",
    origin: "Traditional (American river shanty, early 1800s)",
    publicDomain:
      "Traditional American river shanty, collected and printed through the 19th century.",
    bpm: 66,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Sea Shanty",
    era: "1800s",
    language: "English",
    tags: ["ballad", "legato", "long tones"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "Oh" },
      { midi: 64, startBeat: 1, durBeats: 1, lyric: "Shen", wordEnd: false },
      { midi: 65, startBeat: 2, durBeats: 1, lyric: "an", wordEnd: false },
      { midi: 67, startBeat: 3, durBeats: 2, lyric: "doah," },
      { midi: 67, startBeat: 5, durBeats: 1, lyric: "I" },
      { midi: 69, startBeat: 6, durBeats: 2, lyric: "long" },
      { midi: 67, startBeat: 8, durBeats: 1, lyric: "to" },
      { midi: 64, startBeat: 9, durBeats: 1, lyric: "hear" },
      { midi: 67, startBeat: 10, durBeats: 2, lyric: "you" },
    ],
  },
  {
    // Dorian: the raised sixth on "to" is the tune's signature color.
    id: "scarborough-fair",
    slug: "scarborough-fair",
    title: "Scarborough Fair",
    origin: "Traditional (English ballad, 17th century)",
    publicDomain:
      "Traditional English ballad, documented from the 17th century onward.",
    bpm: 96,
    beatsPerBar: 3,
    defaultKeyRootMidi: 62,
    form: "phrase",
    defaultLoops: 4,
    genre: "Folk",
    era: "1600s",
    language: "English",
    tags: ["ballad", "modal", "dorian"],
    notes: [
      { midi: 62, startBeat: 0, durBeats: 1, lyric: "Are" },
      { midi: 62, startBeat: 1, durBeats: 1, lyric: "you" },
      { midi: 69, startBeat: 2, durBeats: 2, lyric: "go", wordEnd: false },
      { midi: 69, startBeat: 4, durBeats: 1, lyric: "ing" },
      { midi: 71, startBeat: 5, durBeats: 1, lyric: "to" },
      { midi: 69, startBeat: 6, durBeats: 2, lyric: "Scar", wordEnd: false },
      { midi: 67, startBeat: 8, durBeats: 1, lyric: "bo", wordEnd: false },
      { midi: 64, startBeat: 9, durBeats: 1, lyric: "rough" },
      { midi: 62, startBeat: 10, durBeats: 3, lyric: "Fair?" },
    ],
  },
  {
    // Full arrangement: verse 1 is the phrase entry's melody; verse 2 repeats
    // the exact same tune (this hymn is strophic — every stanza reuses it)
    // with the second stanza of Newton's original text. Two passes of the
    // phrase's own range-plus-leaps keep it Hard across the whole thing.
    id: "amazing-grace-full",
    slug: "amazing-grace-full",
    title: "Amazing Grace (Verse 1 & 2)",
    origin: "Traditional tune “New Britain” (American shape-note, printed 1829); words by John Newton, 1779",
    publicDomain:
      "John Newton’s hymn text — including this second stanza — was published in his 1779 Olney Hymns; the “New Britain” tune it is now sung to first appeared in an 1829 shape-note tunebook. Both are centuries out of copyright.",
    bpm: 70,
    beatsPerBar: 3,
    defaultKeyRootMidi: 60,
    form: "full",
    defaultLoops: 1,
    genre: "Hymn",
    era: "1700s",
    language: "English",
    tags: ["hymn", "wide range", "leap", "full song", "two verses"],
    arrangementOf: "amazing-grace",
    notes: [
      { midi: 67, startBeat: 0, durBeats: 1, lyric: "A", wordEnd: false },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "maz", wordEnd: false },
      { midi: 64, startBeat: 2, durBeats: 1, lyric: "ing" },
      { midi: 60, startBeat: 3, durBeats: 2, lyric: "grace," },
      { midi: 64, startBeat: 5, durBeats: 1, lyric: "how" },
      { midi: 62, startBeat: 6, durBeats: 1, lyric: "sweet" },
      { midi: 60, startBeat: 7, durBeats: 1, lyric: "the" },
      { midi: 57, startBeat: 8, durBeats: 2, lyric: "sound," },
      { midi: 67, startBeat: 10, durBeats: 1, lyric: "that", line: 1 },
      { midi: 60, startBeat: 11, durBeats: 1, lyric: "saved", line: 1 },
      { midi: 64, startBeat: 12, durBeats: 1, lyric: "a", line: 1 },
      { midi: 60, startBeat: 13, durBeats: 1, lyric: "wretch", line: 1 },
      { midi: 64, startBeat: 14, durBeats: 1, lyric: "like", line: 1 },
      { midi: 62, startBeat: 15, durBeats: 3, lyric: "me", line: 1 },
      { midi: 67, startBeat: 18, durBeats: 1, lyric: "'Twas", line: 2 },
      { midi: 60, startBeat: 19, durBeats: 1, lyric: "grace", line: 2 },
      { midi: 64, startBeat: 20, durBeats: 1, lyric: "that", line: 2 },
      { midi: 60, startBeat: 21, durBeats: 2, lyric: "taught,", line: 2 },
      { midi: 64, startBeat: 23, durBeats: 1, lyric: "my", line: 2 },
      { midi: 62, startBeat: 24, durBeats: 1, lyric: "heart", line: 2 },
      { midi: 60, startBeat: 25, durBeats: 1, lyric: "to", line: 2 },
      { midi: 57, startBeat: 26, durBeats: 2, lyric: "fear,", line: 2 },
      { midi: 67, startBeat: 28, durBeats: 1, lyric: "And", line: 3 },
      { midi: 60, startBeat: 29, durBeats: 1, lyric: "grace", line: 3 },
      { midi: 64, startBeat: 30, durBeats: 1, lyric: "my", line: 3 },
      { midi: 60, startBeat: 31, durBeats: 1, lyric: "fears", line: 3 },
      { midi: 64, startBeat: 32, durBeats: 1, lyric: "re", line: 3, wordEnd: false },
      { midi: 62, startBeat: 33, durBeats: 3, lyric: "lieved;", line: 3 },
    ],
    sections: [
      { kind: "verse", label: "Verse 1", startBeat: 0, endBeat: 18 },
      { kind: "verse", label: "Verse 2", startBeat: 18, endBeat: 36 },
    ],
  },
  {
    // Two identical fifth-leaps on "Bonnie" (start of each line) anchor an
    // otherwise stepwise descent — Hard on the leaps alone.
    id: "my-bonnie",
    slug: "my-bonnie-lies-over-the-ocean",
    title: "My Bonnie Lies Over the Ocean",
    origin: "Traditional Scottish/English folk song, in print since the 1880s",
    publicDomain:
      "Traditional folk song of unknown authorship; sheet-music printings were in circulation by the 1880s, and no copyright has ever attached to the tune or lyric.",
    bpm: 108,
    beatsPerBar: 3,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Folk",
    era: "1800s",
    language: "English",
    tags: ["ballad", "waltz", "leap"],
    notes: [
      { midi: 60, startBeat: 0, durBeats: 1, lyric: "My" },
      { midi: 67, startBeat: 1, durBeats: 1, lyric: "Bon", wordEnd: false },
      { midi: 67, startBeat: 2, durBeats: 1, lyric: "nie" },
      { midi: 65, startBeat: 3, durBeats: 1, lyric: "lies" },
      { midi: 64, startBeat: 4, durBeats: 1, lyric: "o", wordEnd: false },
      { midi: 62, startBeat: 5, durBeats: 1, lyric: "ver" },
      { midi: 60, startBeat: 6, durBeats: 1, lyric: "the" },
      { midi: 62, startBeat: 7, durBeats: 1, lyric: "o", wordEnd: false },
      { midi: 64, startBeat: 8, durBeats: 2, lyric: "cean," },
      { midi: 60, startBeat: 10, durBeats: 1, lyric: "my", line: 1 },
      { midi: 67, startBeat: 11, durBeats: 1, lyric: "Bon", line: 1, wordEnd: false },
      { midi: 67, startBeat: 12, durBeats: 1, lyric: "nie", line: 1 },
      { midi: 65, startBeat: 13, durBeats: 1, lyric: "lies", line: 1 },
      { midi: 64, startBeat: 14, durBeats: 1, lyric: "o", line: 1, wordEnd: false },
      { midi: 62, startBeat: 15, durBeats: 1, lyric: "ver", line: 1 },
      { midi: 60, startBeat: 16, durBeats: 1, lyric: "the", line: 1 },
      { midi: 58, startBeat: 17, durBeats: 3, lyric: "sea,", line: 1 },
    ],
  },
  {
    // Text-painting leap down on "low," leap back up on "sweet," and a
    // full-octave climb-and-drop through "carry me home" — Hard on both
    // range and leap count.
    id: "swing-low",
    slug: "swing-low-sweet-chariot",
    title: "Swing Low, Sweet Chariot",
    origin: "Traditional African American spiritual, often attributed to Wallace Willis (pre-1862)",
    publicDomain:
      "Traditional spiritual, often attributed to Wallace Willis before 1862; first published in the Fisk Jubilee Singers’ 1872 songbook “Jubilee Songs.” Long out of copyright.",
    bpm: 84,
    beatsPerBar: 4,
    defaultKeyRootMidi: 60,
    form: "phrase",
    defaultLoops: 4,
    genre: "Spiritual",
    era: "1800s",
    language: "English",
    tags: ["spiritual", "wide range", "leap"],
    notes: [
      { midi: 67, startBeat: 0, durBeats: 1, lyric: "Swing" },
      { midi: 60, startBeat: 1, durBeats: 1, lyric: "low," },
      { midi: 67, startBeat: 2, durBeats: 1, lyric: "sweet" },
      { midi: 65, startBeat: 3, durBeats: 1, lyric: "char", wordEnd: false },
      { midi: 64, startBeat: 4, durBeats: 1, lyric: "i", wordEnd: false },
      { midi: 62, startBeat: 5, durBeats: 2, lyric: "ot," },
      { midi: 67, startBeat: 7, durBeats: 1, lyric: "com", line: 1, wordEnd: false },
      { midi: 69, startBeat: 8, durBeats: 1, lyric: "ing", line: 1 },
      { midi: 67, startBeat: 9, durBeats: 1, lyric: "for", line: 1 },
      { midi: 65, startBeat: 10, durBeats: 1, lyric: "to", line: 1 },
      { midi: 67, startBeat: 11, durBeats: 1, lyric: "car", line: 1, wordEnd: false },
      { midi: 72, startBeat: 12, durBeats: 1, lyric: "ry", line: 1 },
      { midi: 69, startBeat: 13, durBeats: 1, lyric: "me", line: 1 },
      { midi: 60, startBeat: 14, durBeats: 3, lyric: "home,", line: 1 },
    ],
  },
];

export const ALL_SONGS: Song[] = [...SONGS, ...PRO_SONGS];

/** Look up a song by its URL slug, across both books. */
export function songBySlug(slug: string): Song | undefined {
  return ALL_SONGS.find((s) => s.slug === slug);
}

/** Whether a song id belongs to the Pro-gated book. */
export function isProSong(id: string): boolean {
  return PRO_SONGS.some((s) => s.id === id);
}
