import curriculumContract from "@/contracts/suede-voice-curriculum.json";

export interface VoiceLesson {
  readonly id: string;
  readonly title: string;
  readonly type: string;
  readonly minutes: number;
  readonly summary: string;
}

export interface VoiceModule {
  readonly id: string;
  readonly name: string;
  readonly promise: string;
  readonly skill: string;
  readonly proofMetric: string;
  readonly lessonsTotal: number;
  readonly sampleLessonsShown: number;
  readonly lessons: readonly VoiceLesson[];
}

export interface VoiceLevel {
  readonly id: string;
  readonly name: string;
  readonly subtitle: string;
  readonly access: "free" | "paid";
  readonly moduleCount: number;
  readonly lessonCount: number;
  readonly stage: number;
  readonly modules: readonly VoiceModule[];
}

export interface VoiceCurriculumContract {
  readonly contract: "suede-voice-curriculum";
  readonly version: 1;
  readonly ownership: {
    readonly catalogRepository: "JasonColapietro/sing";
    readonly discoveryUrl: "https://sing.suedeai.ai/learn";
    readonly lessonHostRepository: "JasonColapietro/sing";
    readonly lessonBaseUrl: "https://sing.suedeai.ai/learn/voice";
    /** When the owner moved the lesson bodies to sing. */
    readonly hostingDecisionDate: "2026-09-23";
    /** When the classifier and import policies below were decided. */
    readonly decisionDate: "2026-09-14";
    readonly decidedBy: "Jason Colapietro (delegated decision)";
  };
  readonly policies: {
    readonly classifierLabels: readonly [
      "bass",
      "baritone",
      "tenor",
      "contralto",
      "mezzo",
      "soprano",
    ];
    readonly importedSessionCompletion: "historyOnly";
  };
  readonly migration: {
    readonly phase: "hosted";
    readonly redirectsEnabled: true;
    readonly previousLessonBaseUrl: "https://guitarhub.org/learn/voice";
    /** Where each old lesson URL goes. Generated by scripts/compile-lessons.mjs. */
    readonly urlMap: "contracts/suede-voice-lesson-urls.json";
    readonly requiredEvidence: readonly [
      "lessonBodies",
      "identity",
      "entitlements",
      "progress",
      "urlParity",
      "vocalReview",
      "deviceAudio",
    ];
    /** What happened to each piece of required evidence, stated rather than implied. */
    readonly resolution: Readonly<Record<(typeof REQUIRED_EVIDENCE)[number], string>>;
  };
  readonly curriculum: {
    readonly track: "voice";
    readonly version: number;
    readonly levels: readonly VoiceLevel[];
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isString(value: unknown): value is string {
  return typeof value === "string";
}

function isNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isVoiceLesson(value: unknown): value is VoiceLesson {
  return (
    isRecord(value) &&
    isString(value.id) &&
    isString(value.title) &&
    isString(value.type) &&
    isNumber(value.minutes) &&
    isString(value.summary)
  );
}

function isVoiceModule(value: unknown): value is VoiceModule {
  return (
    isRecord(value) &&
    isString(value.id) &&
    isString(value.name) &&
    isString(value.promise) &&
    isString(value.skill) &&
    isString(value.proofMetric) &&
    isNumber(value.lessonsTotal) &&
    isNumber(value.sampleLessonsShown) &&
    // An empty array passes `every`, so a module with no lessons (or a level
    // with no modules, below) has to be refused explicitly.
    Array.isArray(value.lessons) &&
    value.lessons.length > 0 &&
    value.lessons.every(isVoiceLesson)
  );
}

function isVoiceLevel(value: unknown): value is VoiceLevel {
  return (
    isRecord(value) &&
    isString(value.id) &&
    isString(value.name) &&
    isString(value.subtitle) &&
    (value.access === "free" || value.access === "paid") &&
    isNumber(value.moduleCount) &&
    isNumber(value.lessonCount) &&
    isNumber(value.stage) &&
    Array.isArray(value.modules) &&
    value.modules.length > 0 &&
    value.modules.every(isVoiceModule)
  );
}

function matchesTuple(
  value: unknown,
  expected: readonly string[],
): value is readonly string[] {
  return (
    Array.isArray(value) &&
    value.length === expected.length &&
    value.every((item, index) => item === expected[index])
  );
}

const CLASSIFIER_LABELS = [
  "bass",
  "baritone",
  "tenor",
  "contralto",
  "mezzo",
  "soprano",
] as const;

const REQUIRED_EVIDENCE = [
  "lessonBodies",
  "identity",
  "entitlements",
  "progress",
  "urlParity",
  "vocalReview",
  "deviceAudio",
] as const;

function isVoiceCurriculumContract(
  value: unknown,
): value is VoiceCurriculumContract {
  if (!isRecord(value)) return false;
  const { ownership, policies, migration, curriculum } = value;
  return (
    value.contract === "suede-voice-curriculum" &&
    value.version === 1 &&
    isRecord(ownership) &&
    ownership.catalogRepository === "JasonColapietro/sing" &&
    ownership.discoveryUrl === "https://sing.suedeai.ai/learn" &&
    ownership.lessonHostRepository === "JasonColapietro/sing" &&
    ownership.lessonBaseUrl === "https://sing.suedeai.ai/learn/voice" &&
    ownership.hostingDecisionDate === "2026-09-23" &&
    ownership.decisionDate === "2026-09-14" &&
    ownership.decidedBy === "Jason Colapietro (delegated decision)" &&
    isRecord(policies) &&
    matchesTuple(policies.classifierLabels, CLASSIFIER_LABELS) &&
    policies.importedSessionCompletion === "historyOnly" &&
    isRecord(migration) &&
    migration.phase === "hosted" &&
    migration.redirectsEnabled === true &&
    migration.previousLessonBaseUrl === "https://guitarhub.org/learn/voice" &&
    migration.urlMap === "contracts/suede-voice-lesson-urls.json" &&
    matchesTuple(migration.requiredEvidence, REQUIRED_EVIDENCE) &&
    isRecord(migration.resolution) &&
    REQUIRED_EVIDENCE.every((key) => isString((migration.resolution as Record<string, unknown>)[key])) &&
    isRecord(curriculum) &&
    curriculum.track === "voice" &&
    isNumber(curriculum.version) &&
    Array.isArray(curriculum.levels) &&
    curriculum.levels.every(isVoiceLevel)
  );
}

/**
 * Validate the checked-in JSON at the untyped data boundary before rendering.
 */
export function parseVoiceCurriculum(
  value: unknown,
): VoiceCurriculumContract {
  if (!isVoiceCurriculumContract(value)) {
    throw new Error("Invalid voice curriculum contract");
  }
  return value;
}

export const voiceCurriculum = parseVoiceCurriculum(curriculumContract);
