/**
 * The glossary contract: the shared vocabulary of Suede's two instruments, and
 * which site owns each word.
 *
 * The glossary started as one app's reference page and is now a set two sites
 * read. GuitarHub ships words like `fret`, `capo`, `twang` and `onset` to
 * beginners undefined, and four words — `register`, `support`, `tone`, `mix` —
 * mean different things depending on which instrument is in the room. A reader
 * who meets "register" in a guitar lesson and then in a voice lesson is being
 * told two things by one word.
 *
 * So the set carries a `domain` per entry, and exactly one site publishes each
 * term: `publisherFor` sends the voice and music vocabulary here, where the
 * rooms that use those words are, and the guitar senses to the guitar hub, which
 * renders them with no structured data at all. Two sites emitting `DefinedTerm`
 * markup for one term would compete with each other as the definitional source
 * for it.
 *
 * The whole set is serialized, guitar senses included, because the consumer
 * needs every entry either way: it renders the guitar ones and links the voice
 * and music ones here rather than leaving a word bare.
 *
 * It is generated, not written: `lib/glossary.ts` is the source and this module
 * only reshapes it. See contracts/README.md.
 */
import {
  GLOSSARY,
  GLOSSARY_TERMS,
  glossaryKey,
  publisherFor,
  termId,
  type GlossaryDomain,
  type GlossaryEntry,
  type GlossaryPublisher,
} from "@/lib/glossary";

/**
 * Bumped only when the shape changes — a key added, removed or renamed. A new
 * term is not a version bump: a consumer should meet that as a changed file,
 * not as a version it is allowed to ignore.
 */
export const CONTRACT_VERSION = 1;

const DOMAINS: GlossaryDomain[] = ["music", "voice", "guitar"];
const PUBLISHERS: GlossaryPublisher[] = ["sing", "guitarHub"];

/**
 * `aka` is optional on the source type and is written as an empty array here
 * rather than omitted. `JSON.stringify` drops an undefined value silently, so an
 * omitted key reads to a consumer as "this term has no other names" and to a
 * reviewer as nothing at all.
 */
function serializeEntry(entry: GlossaryEntry) {
  return {
    /** Domain-qualified, because `register` and `tone` each exist twice. */
    key: glossaryKey(entry),
    term: entry.term,
    /** The anchor within one site's page; not unique across the set. */
    anchor: termId(entry.term),
    aka: entry.aka ?? [],
    definition: entry.definition,
    where: entry.where,
    href: entry.href,
    domain: entry.domain,
    /** Derived from the domain, never restated by hand. */
    publisher: publisherFor(entry.domain),
  };
}

function countBy<K extends string>(keys: K[], of: (entry: GlossaryEntry) => K) {
  return Object.fromEntries(
    keys.map((key) => [key, GLOSSARY_TERMS.filter((e) => of(e) === key).length]),
  ) as Record<K, number>;
}

/** The contract, built from the glossary the app itself renders. */
export function buildContract() {
  return {
    contract: "suede-glossary",
    version: CONTRACT_VERSION,
    reference: {
      repo: "JasonColapietro/sing",
      modules: ["lib/glossary.ts"],
      note: "Generated by contracts/glossary.ts. Do not hand-edit; run the regenerate command in contracts/README.md.",
      publishing:
        "One site publishes each term. Entries with publisher sing are rendered with DefinedTerm markup at /glossary in JasonColapietro/sing; entries with publisher guitarHub are rendered by the guitar hub with no structured data, so the two sites do not compete as the definitional source for one word.",
    },
    counts: {
      total: GLOSSARY_TERMS.length,
      byDomain: countBy(DOMAINS, (e) => e.domain),
      byPublisher: countBy(PUBLISHERS, (e) => publisherFor(e.domain)),
    },
    /** Reading order, exactly as the source declares it. */
    sections: GLOSSARY.map((section) => ({
      heading: section.heading,
      anchor: termId(section.heading),
      blurb: section.blurb,
      entries: section.entries.map(serializeEntry),
    })),
  };
}

export type GlossaryContract = ReturnType<typeof buildContract>;

/** The exact bytes the committed file holds: 2-space indent, trailing newline. */
export function serializeContract(contract: unknown = buildContract()): string {
  return `${JSON.stringify(contract, null, 2)}\n`;
}
