/**
 * The shape of a singer's practice record, published so GuitarHub can read one
 * without guessing.
 *
 * ## Why this repository is the reference surface, and not the other one
 *
 * GuitarHub holds the other half of the cross-application story: an append-only
 * attempt ledger keyed to authored lesson identifiers, validated by
 * `parseLearningAttempt`, which refuses any identifier outside the caller's
 * `allowedLessons`. That is the side with hard validation and the side that can
 * say no, so the instinct is to let it own the agreement. The instinct is half
 * right, and the half it gets wrong is the expensive one.
 *
 * A contract should be generated by whoever runs the code it describes. The
 * record described here exists in this repository and nowhere else: `sessions`,
 * `streak`, `xp`, `range` and `rangeHistory` are this app's types, validated by
 * this app's three entry points in lib/progress-shape.ts, repaired by this app's
 * `sanitizeProgress`. GuitarHub has no session-shaped record at all. If the
 * shape were declared over there it would be a transcription, and a
 * transcription cannot fail when the original moves — which is the whole
 * failure mode the contracts in this directory exist to remove. The same rule
 * already decides the other three: `suede-vocal.json` and `glossary.json` are
 * authored here because the numbers and the words are here, and GuitarHub's
 * `web-practice.json` is authored there because its detector is there.
 *
 * What GuitarHub owns instead is the *mapping* — what a session of each activity
 * type counts as against its curriculum. That is the right split, because it is
 * the split along which each claim is checkable. Lesson identifiers are authored
 * in GuitarHub's curriculum and are meaningless here; a mapping table published
 * from this repository would be an assertion about a catalog this repository
 * cannot see and could not revalidate when a lesson is renamed. So: this side
 * publishes what a session *is*, that side decides what a session *counts as*,
 * and a test fails on whichever side moved.
 *
 * ## What is deliberately not here
 *
 * XP and the streak are described and marked unimportable rather than omitted,
 * because a consumer reading a real exported record will meet both fields and
 * needs to be told what to do with them. See the `portability` section: the
 * reasoning is part of the payload, not a comment, because the consumer is
 * another repository and cannot read this file.
 *
 * The XP *numbers* are not repeated here. They are already serialized in
 * contracts/practice-parity.json under `progress.xpEarn`, and two contracts in
 * one directory carrying one set of numbers is the drift this directory exists
 * to prevent. This one carries a pointer, and the test asserts the pointer
 * resolves.
 *
 * Regenerate with:
 *   CONTRACT_WRITE=1 npx vitest run contracts/suede-progress.test.ts
 */
import type { NoteTallies, RangeEntry } from "@/lib/analytics";
import { PROGRESS_STORAGE_KEY } from "@/lib/progress";
import {
  ACTIVITY_TYPES,
  DEFAULT_PROGRESS,
  MAX_ACHIEVEMENTS,
  MAX_NOTE_KEYS,
  MAX_RANGE_HISTORY,
  MAX_SESSIONS,
  MAX_STRING,
  MAX_XP,
  WARMUP_MODES,
  isValidRange,
  isValidRangeEntry,
  isValidSession,
  type SessionLog,
  type VocalRange,
} from "@/lib/progress-shape";

export const CONTRACT_NAME = "suede-progress-shape";

/**
 * Bumped only when the shape changes — a key added, removed or renamed. A
 * changed value is not a version bump; it is the thing the contract exists to
 * surface, and the consumer should meet it as a failing byte comparison rather
 * than as a version it can decide to skip.
 */
export const CONTRACT_VERSION = 1;

/** Asserted against the serialized file, so a new top-level key has to be added
 * here in the same commit and cannot arrive unreviewed. */
export const CONTRACT_KEYS = [
  "caps",
  "contract",
  "portability",
  "range",
  "record",
  "reference",
  "session",
  "storage",
  "version",
] as const;

/**
 * A session with every field present, including the optional ones.
 *
 * Typed `Required<SessionLog>` on purpose: adding a field to `SessionLog`
 * without adding it here is a type error, so the published field list cannot
 * silently fall behind the interface. The values are only ever fed to the
 * validator, never stored.
 */
const SESSION_SPECIMEN: Required<SessionLog> = {
  id: "specimen",
  type: "warmup",
  date: "2026-01-01T12:00:00.000Z",
  day: "2026-01-01",
  durationSec: 60,
  score: 80,
  detail: "Specimen",
  xp: 10,
  notes: { "60": { sec: 4, hitSec: 3, cents: 12, frames: 180 } } satisfies NoteTallies,
  mode: "sing-along",
};

/** The latest-range block, every field present. Same `Required<…>` guard. */
const RANGE_SPECIMEN: Required<VocalRange> = {
  lowMidi: 48,
  highMidi: 72,
  voiceType: "baritone",
  voiceTypeLabel: "Baritone",
  testedAt: "2026-01-01T12:00:00.000Z",
};

/** One entry of the range-test history, every field present. */
const RANGE_ENTRY_SPECIMEN: Required<RangeEntry> = {
  lowMidi: 48,
  highMidi: 72,
  testedAt: "2026-01-01T12:00:00.000Z",
  voiceTypeLabel: "Baritone",
};

/**
 * Which fields the live validator insists on, found by asking it rather than by
 * restating it.
 *
 * The alternative was a hand-written list of required and optional field names,
 * which is a second opinion about the validator that can disagree with it
 * silently — a field made optional in lib/progress-shape.ts would leave this
 * contract telling GuitarHub it is mandatory, and an importer would reject real
 * records for missing something the writer stopped writing. Dropping each field
 * in turn and asking the validator what it thinks cannot drift, because there is
 * only one opinion in the building.
 *
 * Throws if the specimen itself is rejected: without that guard a broken
 * specimen publishes every field as required, which is a wrong contract that
 * looks like a thorough one.
 */
function fieldRequirement<T extends Record<string, unknown>>(
  what: string,
  specimen: T,
  accept: (value: unknown) => boolean,
) {
  if (!accept(specimen)) {
    throw new Error(
      `The ${what} specimen in contracts/suede-progress.ts is rejected by its own validator, ` +
        `so the published field list would be meaningless. Fix the specimen.`,
    );
  }
  const required: string[] = [];
  const optional: string[] = [];
  for (const key of Object.keys(specimen).sort()) {
    const without: Record<string, unknown> = { ...specimen };
    delete without[key];
    (accept(without) ? optional : required).push(key);
  }
  return { required, optional };
}

export function buildContract() {
  return {
    contract: CONTRACT_NAME,
    version: CONTRACT_VERSION,
    /**
     * Stated in the payload because the consumer is another repository and
     * cannot read the docstring above it.
     */
    reference:
      "JasonColapietro/sing is the reference surface for this shape: the record, " +
      "its validators and its caps are implemented here and nowhere else, so the " +
      "contract is generated rather than transcribed. The session-to-lesson mapping " +
      "is deliberately not here — lesson identifiers are authored in " +
      "JasonColapietro/suede-guitar-hub, which is the only side that can revalidate " +
      "them, so that side owns the mapping and this side owns the shape.",
    storage: {
      medium: "localStorage",
      key: PROGRESS_STORAGE_KEY,
      note:
        "An exported record is the stored record, serialized with two-space " +
        "indentation by exportProgress(). There is no separate export envelope and " +
        "no wrapper version field: the key's own suffix is the schema version.",
    },
    record: {
      /** From `DEFAULT_PROGRESS`, so the list is the type's and not a memory of it. */
      fields: Object.keys(DEFAULT_PROGRESS).sort(),
      identity:
        "A file is recognisably one of ours when it is an object with a finite xp " +
        "and an array of sessions. Those two fields have been present since the " +
        "first release; everything else can legitimately be missing from an old " +
        "backup and is repaired on read.",
    },
    session: {
      activityTypes: [...ACTIVITY_TYPES],
      warmupModes: [...WARMUP_MODES],
      ...fieldRequirement("session", SESSION_SPECIMEN, isValidSession),
      scoreScale:
        "score is a percentage from 0 to 100 and is absent for activities that " +
        "score nothing. It is not a cents deviation and not a star count.",
      unscorable:
        "id, type and day are required because none of them can be guessed from " +
        "the rest of a row: type selects the label and colour, day is what the " +
        "streak and the calendar group by, and minting an id would let the same " +
        "practice reappear as a duplicate on the next merge.",
    },
    range: {
      latest: fieldRequirement("latest range", RANGE_SPECIMEN, isValidRange),
      test: fieldRequirement("range test", RANGE_ENTRY_SPECIMEN, isValidRangeEntry),
      note:
        "rangeHistory is every test, oldest first, and range is the last of them. " +
        "A session of type 'range' does not itself carry the measured span: the " +
        "span lives in rangeHistory, matched to the session by day.",
    },
    caps: {
      maxSessions: MAX_SESSIONS,
      maxRangeHistory: MAX_RANGE_HISTORY,
      maxAchievements: MAX_ACHIEVEMENTS,
      maxXp: MAX_XP,
      maxNoteKeys: MAX_NOTE_KEYS,
      maxString: MAX_STRING,
      note:
        "These are refusal boundaries at an API and trimming boundaries in a " +
        "browser: a server must reject an over-cap payload rather than reshape a " +
        "record the singer did not agree to, while a browser reading its own " +
        "storage keeps what is still meaningful because those bytes are the only " +
        "copy.",
    },
    /**
     * Per field group: may a consumer turn this into its own record, and why
     * not. The reasons are payload rather than comment because the consumer is
     * another repository; a verdict with no reason gets overturned by whoever
     * next wants the field.
     */
    portability: {
      sessions: {
        importable: true,
        because:
          "A session is an observation: an activity type, a day, a duration and " +
          "sometimes a percentage. A consumer can record that it happened. What a " +
          "session does not carry is a lesson identifier, so it cannot establish " +
          "progress through a curriculum by itself — that is what the importing " +
          "side's mapping has to decide.",
      },
      range: {
        importable: true,
        because:
          "A measured low and high MIDI note with a timestamp is the one part of " +
          "this record that means the same thing in any application that knows " +
          "what a voice is.",
      },
      achievements: {
        importable: false,
        because:
          "An achievement id names a rule defined only in this repository, and the " +
          "ids are checked against nothing on the way in. Importing them would " +
          "give the consumer a list of strings it cannot interpret and cannot " +
          "verify.",
      },
      xp: {
        importable: false,
        definedIn: "contracts/practice-parity.json#progress.xpEarn",
        because:
          "XP is derived from duration with a floor, a ceiling and score bonuses, " +
          "so it measures how long somebody practised and is not evidence about " +
          "what they can do. GuitarHub's attempt ledger has no field for it: it " +
          "could only land in an attempt's free-form details, where it would be a " +
          "number nothing validates and something would eventually render as " +
          "though it had been earned there.",
      },
      streak: {
        importable: false,
        definition:
          "current is the number of consecutive local calendar days ending at the " +
          "most recent session day, best is the longest such run, and lastDay is " +
          "the day key the count ends on. Local days, not UTC, and walked by the " +
          "calendar rather than by subtracting 86,400,000 milliseconds.",
        because:
          "This is a decision rather than a missing field. GuitarHub argues in " +
          "published copy that a streak measures attendance — it rises on a " +
          "session that changed nothing and resets on a week off that changed a " +
          "lot — and ships no streak counter on purpose. A contract that carried " +
          "the number across would import a thing that repository has decided " +
          "against, and the first surface that found the field would quietly " +
          "reverse the decision. The definition is published anyway so that nobody " +
          "needing a streak re-derives one differently, and the number is not.",
      },
    },
  };
}

/** The bytes the committed file should hold. Two spaces and a trailing newline,
 * because a generated file that fights the formatter gets regenerated wrong once
 * and then nobody trusts the check again. */
export function serializeContract() {
  return `${JSON.stringify(buildContract(), null, 2)}\n`;
}
